parkering/account/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [

    # display index screen
	url(r'^$', views.Index.Index_screen, name='Index_screen'),

    # used for login function
	url(r'^login/auth$', views.Login.Login_check, name='Login_check'),

    # used for logout function
	url(r'^logout$', views.Logout.Logout, name='Logout'),

    # display login screen
    url(r'^login$', views.Login.Login_screen, name='Login_screen'),

    # display register screen
    url(r'^register$', views.Register.Register_screen, name='Register_screen'),

    # display forgot password view
    url(r'^forgot_password$', views.ForgotPassword.Forgot_password_screen, name='Forgot_password_screen'),

    # used for register account function
    url(r'^register_account$', views.Register.Register_account, name='Register_account'),

    # display account management
    url(r'^account_management$', views.AccountManagement.Account_screen, name='Account_screen'),

    # display not authorized page
    url(r'^not_authorized$', views.Error.Authorization_failed, name='Authorization_failed'),

    # display update password page
    url(r'^update_password$', views.AccountManagement.UpdatePass_screen, name='UpdatePass_screen'),

    # used for update password function
    url(r'^update_password/update$', views.AccountManagement.Update_password, name='Update_password'),

    # display update password page
    url(r'^update_details$', views.AccountManagement.UpdateDetails_screen, name='UpdateDetails_screen'),

    # display update password page
    url(r'^update_details/update$', views.AccountManagement.Update_details, name='Update_details'),

    # the built-in password reset view.
    url(r'^reset_password$', views.ForgotPassword.Reset, name='reset'),
    
    # reset confirmation view, used with the password email reset link.
    url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.ForgotPassword.Reset_confirm, name='password_reset_confirm'),
]

parkering/kombo_parking/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'kombo_parking'

urlpatterns = [
    # url(r'^calendar/$', views.frontpage, name='frontpage'),
    url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^calendar_click/$', views.calendar_click, name='calendar_click'),
    url(r'^grab_parkingspace/', views.grab_parkingspace),    
    url(r'^rentout_your_space_to_people/$', views.rentout_your_space_to_people, name='rentout_your_space_to_people'),
]

parkering/main/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'main'

urlpatterns = [

	# display index view
    url(r'^$', views.Let_there_be_light, name='Render_all'),    

    # display FAQ
    url(r'^faq$', views.FAQ_screen, name='FAQ_screen'),

    # display test view
    url(r'^test$', views.Test, name='Test'),
]

parkering/parkering/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index')
]

parkering/parking/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^', include('account.urls')),
    url(r'^', include('kombo_parking.urls')),
]

parkering/kombo_parking/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# DB User parking spaces
class Parking_space(models.Model):
    number = models.IntegerField(unique=True)
    owner = models.ForeignKey(User)
    
    def __str__(self):
        return "%s - %s %s"%(str(self.number),str(self.owner.first_name),str(self.owner.last_name))


# DB bookings. Available and taken.        
class Booking(models.Model):
    space = models.ForeignKey(Parking_space)
    owner = models.ForeignKey(User, null=True, blank=True)
    taken = models.BooleanField(default=False)
    start_date = models.DateTimeField()
    stop_date = models.DateTimeField()

    def clean(self):
        if self.start_date >= self.stop_date:
            raise ValidationError("Stop date cannot be earlier than the start date!")

    def save(self, *args, **kwargs):
        self.clean()

        super(Booking, self).save(*args, **kwargs)
          
    def __str__(self):
        if self.owner:
            return "%s - %s, %s -> %s booked by %s %s"%(self.space.number, "Taken" if self.taken is True else "Available", self.start_date, self.stop_date, self.owner.first_name, self.owner.last_name)
        else:
            return "%s - %s -> %s" % (self.space.number, self.start_date, self.stop_date)

#DB Requests            
class Requested_Space(models.Model):
    renter = models.ForeignKey(User)
    start_date = models.DateTimeField()
    stop_date = models.DateTimeField()
        
    def clean(self):
        if self.start_date >= self.stop_date:
            raise ValidationError("Stop date cannot be earlier than the start date!")

    def save(self, *args, **kwargs):
        self.clean()

        super(Requested_Space, self).save(*args, **kwargs)
          
    def __str__(self):
        return "%s Requests space FROM %s TO %s" % (self.renter, self.start_date, self.stop_date)
        

parkering/kombo_parking/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import auth
from account.models import User_data
from .models import Booking, Parking_space, Requested_Space
from django.contrib.auth import logout
from django.core.mail import EmailMessage
from django.contrib.auth.views import password_reset, password_reset_confirm
from django.core.urlresolvers import reverse
from .forms import Rent_space_form, Request_space_form, Request_to_own_Parking_space, Unregister_Parking_Space
from django.template import loader
from datetime import datetime, timedelta
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.utils.translation import ugettext as _
from django.utils.translation import activate

def get_event_text(request, variable):
    if request.LANGUAGE_CODE == "sv":
        return {
        'Bookings': "Bokningar",
        'Requests': "Förfrågningar",
        'Available': "Lediga",
        }[variable]
    else:
        return variable

# EmailMessage('Kombo Parking', 'Plats: %s uthyrd' % booking.space.number, to=[booking.space.owner.email]).send()
def send_mail(subject, email_to, body,):
    EmailMessage(subject, body, to=[email_to]).send()
      
def calendar_click(request):
    if request.is_ajax():
        if request.POST['date']:
            FILENAME = None
            result_list = []
            
            if "REQUESTS" in request.POST['event_type_magic_string']:
                FILENAME = 'kombo_parking/calendarmodal_REQUESTS.html'
                requests = Requested_Space.objects.filter(start_date__startswith=request.POST['date'])
                
                if requests:
                    for event in requests:
                        result_list.append({
                            'id':event.id,                        
                            'start_date': event.start_date.strftime("%Y-%m-%d %H:%M"),
                            'stop_date': event.stop_date.strftime("%Y-%m-%d %H:%M"),
                            'user' : event.renter,
                        }) 
                html = loader.render_to_string(FILENAME, {
                        'requests': result_list,                    
                        'parking_spaces': Parking_space.objects.filter(owner=request.user).values_list('number', flat=True).order_by('number'),                    
                        'you_have_booked_spaces': True if Booking.objects.filter(start_date__startswith=request.POST['date'],taken=True).filter(owner=request.user) else False,
                        'request': request,
                        
                    })
                
            elif "BOOKINGS" in request.POST['event_type_magic_string']:
                FILENAME = 'kombo_parking/calendarmodal_BOOKINGS.html'
                booked = Booking.objects.filter(start_date__startswith=request.POST['date'],taken=True)
                
                if booked:
                    for event in booked:
                        result_list.append({
                            'id':event.id,
                            'number': event.space.number,
                            'start_date': event.start_date.strftime("%Y-%m-%d %H:%M"),
                            'stop_date': event.stop_date.strftime("%Y-%m-%d %H:%M"),
                            'booked_user_data' : User_data.objects.filter(user=event.owner).get() if User_data.objects.filter(user=event.owner).exists() else None,
                            'booked_user' : User.objects.filter(id=event.owner.id).get(),                       
                        })
                        
                html = loader.render_to_string(FILENAME, {
                        'bookings': result_list,                    
                        'parking_spaces': Parking_space.objects.filter(owner=request.user).values_list('number', flat=True).order_by('number'),                    
                        'you_have_booked_spaces': True if Booking.objects.filter(start_date__startswith=request.POST['date'],taken=True).filter(owner=request.user) else False,
                        'request': request,
                        
                    })
                
            elif "AVAILABLE" in request.POST['event_type_magic_string']:
                FILENAME = 'kombo_parking/calendarmodal_AVAILABLE.html'
                datelist = Booking.objects.filter(start_date__startswith=request.POST['date'],taken=False)
                
                if datelist:
                    for event in datelist:
                        result_list.append({
                            'id':event.id,
                            'number': event.space.number,
                            'start_date': event.start_date.strftime("%Y-%m-%d %H:%M"),
                            'stop_date': event.stop_date.strftime("%Y-%m-%d %H:%M"),
                        })
              
                html = loader.render_to_string(FILENAME, {
                        'list': result_list,                    
                        'parking_spaces': Parking_space.objects.filter(owner=request.user).values_list('number', flat=True).order_by('number'),                    
                        'you_have_booked_spaces': True if Booking.objects.filter(start_date__startswith=request.POST['date'],taken=True).filter(owner=request.user) else False,
                        'request': request,
                        
                    })
                            
            return HttpResponse(html)
    else:
        return redirect("/")

def grab_parkingspace(request):
    ''' IF chosen booking is your own, Deletes your booking, making space bookable.
        Else Books parking space for you.
    '''
    if request.is_ajax():
        if request.POST['booking_id']:
            item = Booking.objects.filter(id=int(request.POST['booking_id'])).get()            
                        
            # Remove your available parking space (if you you uploaded wrong info)
            if item.space.owner == request.user and item.taken == False:
                item.delete()
                
                
            else:            
                # Unbook, make it available to others.
                if item.owner == request.user:
                    item.taken = False
                    item.owner = None
                    item.save()
     
                    if item.space.owner.email:
                        subject = "Parking space %s no longer booked" % (item.space.number)
                        email_to = item.space.owner.email
                        start = item.start_date.strftime("%Y-%m-%d %H:%M")
                        stop = item.stop_date.strftime("%Y-%m-%d %H:%M")
                        body = "Parking space %s no longer booked" % (item.space.number)
                        
                        #send_mail(subject, email_to, body)
     
                #elif item.space.owner == request.user:
                #    item.delete()
                    
                else:
                    item.owner = request.user
                    item.taken = True        
                    
                    # Send emil to the owner of parking space with info who rented it.
                    if item.space.owner.email:
                        subject = "Parking space rented"
                        email_to = item.space.owner.email
                        start = item.start_date.strftime("%Y-%m-%d %H:%M")
                        stop = item.stop_date.strftime("%Y-%m-%d %H:%M")
                        body = "Parking space %s rented to %s %s from %s to %s\nPhone number: %s" % (item.space.number, request.user.first_name, request.user.last_name, start, stop, User_data.objects.filter(user=request.user).get().phone_number)
                                                
                        #send_mail(subject, email_to, body)
                        
                        # Send confirmation email to the user who rented it.
                        subject = "Parking space rented"
                        email_to = request.user.email
                        start = item.start_date.strftime("%Y-%m-%d %H:%M")
                        stop = item.stop_date.strftime("%Y-%m-%d %H:%M")
                        body = "Parking space %s rented.\nDate/time start: %s\nDate/time stop: %s\nOwner phone: %s" % (item.space.number, start, stop, User_data.objects.get(user=item.space.owner).phone_number)
                                                
                        #send_mail(subject, email_to, body)
                        
                    
                    
                     
                    item.save()
                
            return HttpResponse(loader.render_to_string('kombo_parking/calendar.html'))
    else:
        return redirect("/")
        
''' Rents out your Parking space to chosen request'''
def rentout_your_space_to_people(request):
    if request.is_ajax():   
        requested = Requested_Space.objects.filter(id=request.POST['booking_id']).get()
        spaces = Parking_space.objects.values_list('number', flat=True).filter(owner=request.user)
        
        # IF request user is same as logged in user. Remove request.
        if requested.renter.id == request.user.id:
            requested.delete()
         
        else:
            try:
                try_number = int(request.POST['space'])
                if try_number in spaces:
                    book = Booking()
                    book.owner = requested.renter
                    book.taken = True
                    book.space = Parking_space.objects.filter(number=try_number).get()
                    book.start_date = requested.start_date
                    book.stop_date = requested.stop_date
                
                    
                    

parkering/kombo_parking/templates/kombo_parking/body.html
{% load staticfiles %}
{% load i18n %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="calender">{% include 'kombo_parking/calendar.html' %}</div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="col-md-12">
        {% include 'kombo_parking/navbarForms.html' %}
    </div>
</div>
  

parkering/kombo_parking/templates/kombo_parking/calendar.html
<div id="calendar"></div>

<script>
    $(document).ready(function () {
    //~ console.log("{{list}}");
    $calendar_click_spam_fix = true;

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    
    $('#calendar').fullCalendar({
        header: {
            left: 'title',            
            right:  'today, prev, next, prevYear, nextYear'
        },
        displayEventTime: false,
       {% if list %} events: {{ list|safe }}, {% endif %}

        eventClick: function(calEvent, jsEvent, view) {
            if ($calendar_click_spam_fix == true) {
                $calendar_click_spam_fix = false;
                $.ajax({
                    type: "POST",
                    url: "/calendar_click/",
                    data: {
                        'date': calEvent.start.format().substr(0,10),
                        'csrfmiddlewaretoken': csrftoken,
                        'event_type_magic_string' : calEvent.event_type_magic_string,
                    },
                    success: function(newData) {                   
                        $('#modalArea').html(newData);
                        $('#calendarmodal').modal('show');
                       
                        $calendar_click_spam_fix = true;
                    }
               })
           }
        },
    });
    

});
</script>

<div id="modalArea">
    
</div>

parkering/kombo_parking/templates/kombo_parking/calendarmodal.html
{% load staticfiles %}

<div id="calendarmodal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Register Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        {% if not requests and not list and not bookings %}
            <p>No spaces available, use the options in the navbar to request a parking space.</p>            
        {% endif %}
        {% if list %}
           <h2>Available spaces</h2>
          <table class="table">
            <tr>
                <th class="text-center">Space</th>
                <th class="text-center">Start</th>
                <th class="text-center">Stop</th>            
                <th></th>            
            </tr>
            {% for item in list %}
            <tr>
                <td class="dootfacetwentyseven hidden">{{item.id}}</td>
                <td>{{item.number}}</td>
                <td>{{item.start_date}}</td>
                <td>{{item.stop_date}}</td>
                {% if item.number in parking_spaces %}
                <td><button class="fancyButtonclicker">Remove</button></td>
                {% else %}
                <td><button class="fancyButtonclicker">Book</button></td>
               {% endif %}
            </tr>
            {% endfor %}  
                         
          </table>
        {% endif %} 
          
        {% if requests %}
          <h2>Requested spaces</h2>
          
        <table class="table">
            <tr>
                <th class="text-center">Start</th>
                <th class="text-center">Stop</th>            
                <th>Space to give</th>            
                <th></th>            
            </tr>
            {% for item in requests %}
            <tr>
                <td class="ID_for_Give_Space hidden">{{item.id}}</td>
                <td>{{item.start_date}}</td>
                <td>{{item.stop_date}}</td>
                <!-- <td><input id="{{item.id}}" type="text" name="space_to_lend"></td> -->
                
                {% if parking_spaces %}
                <td>
                    <select>
                    {% for space in parking_spaces %}
                        <option value="{{space}}">{{space}}</option>
                    {% endfor %}
                    </select>
                </td>
                
                <td><button class="Give_That_Space">Give space</button></td>
                {% else %}
                <td>No spaces to lend</td>
                <td></td>
                {% endif %}
                
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        
        {% if bookings %} 
            <!-- Step 1: Print out all the bookings you own and can un-book. -->
            {% if you_have_booked_spaces %}
                <h2>Your bookings</h2>
                    <table class="table">
                        <tr>
                            <th class="text-center">Space</th>
                            <th class="text-center">Start</th>
                            <th class="text-center">Stop</th>            
                            <th></th>            
                        </tr>
                {% for booking in bookings %}
                    {% if booking.booked_user.id == request.user.id %}                        
                        <tr>
                            <td class="dootfacetwentyseven hidden">{{booking.id}}</td>
                            <td>{{booking.number}}</td>
                            <td>{{booking.start_date}}</td>
                            <td>{{booking.stop_date}}</td>
                            <td><button class="fancyButtonclicker">Remove</button></td>
                        </tr>                          
                    {% endif %}                
                {% endfor %}  
                    </table> 
            {% endif %}
            
             <!-- Step 2: Print out all the bookings that you do not own. -->
            {% for booking in bookings %}              
                {% if not booking.booked_user.id == request.user.id %}                       
                    <p class="text-left">
                        {{booking.booked_user.first_name}} {{booking.booked_user.last_name}} has booked space {{booking.number}} from {{booking.start_date}} to {{booking.stop_date}}.<br>
                        Contact: {{booking.booked_user_data.phone_number}}
                    </p>                         
                {% endif %}            
            {% endfor %}        
        {% endif %}
        
        
        
        
        
      </div> <!-- MODAL BODY END -->
      <div class="modal-footer">
          <div class="col-6" id="button-switch">
            <button type="button" class="btn btn-default" id="register-button" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<script>
    var csrftoken;
    
   $( document ).ready(function() {
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    csrftoken = getCookie('csrftoken');
    });
    

    
    $(".fancyButtonclicker").click(function() {
        var $item = $(this).closest("tr").find(".dootfacetwentyseven").text();  // Find row of clicked button, get td containing magic id with silly class name.
        console.log($item);
        
        $.ajax({
            type: "POST",
            url: "/grab_parkingspace/",
            data: {
                'booking_id': $item,
                'csrfmiddlewaretoken': csrftoken,
            },
            success: function(data) {
               //alert("Bokat, gör en häftigare notis eller redirect eller något.")           
               location.reload();
            }
       })
    });
    
    
     $(".Give_That_Space").click(function() {
        var $item_id = $(this).closest("tr").find(".ID_for_Give_Space").text();  // Find row of clicked button, get td containing magic id with silly class name.
        var $space = $(this).closest("tr").find("select option:selected").text();  // Find row of clicked button, get td containing magic id with silly class name.                
       
       $.ajax({
            type: "POST",
            url: "/rentout_your_space_to_people/",
            data: {
                'booking_id': $item_id,
                'space':$space,
                'csrfmiddlewaretoken': csrftoken,
            },
            success: function(data) {
               //alert("Bokat, gör en häftigare notis eller redirect eller något.")           
               location.reload();
            }
       })
      
    });
   
    
    
    //~ function(date, jsEvent, view) {
             //~ $.ajax({
                //~ type: "POST",
                //~ url: "/grab_parkingspace/",
                //~ data: {
                    //~ 'booking_id': ,
                    //~ 'csrfmiddlewaretoken': csrftoken,
                //~ },
                //~ success: function(newData) {
                    //~ alert('Farsågod.');
                //~ }
           //~ })
        //~ },
</script>

parkering/kombo_parking/templates/kombo_parking/mainTemplateFooter.html
{% load staticfiles %}
{% load i18n %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div id="calenderFooter">
    <p class="text-muted">
        <p id="footerPargrah">
            © Komboparking
            <a href="{% url 'main:FAQ_screen' %}"> FAQ </a>
        </p>
    </p>
</div>

parkering/kombo_parking/templates/kombo_parking/navbar.html
{% load staticfiles %}
{% load i18n %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<nav class="navbar navbar-default" id="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KomboNav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" id="siteBrand">Kombo Parking</a>
    </div>
    <div class="collapse navbar-collapse" id="KomboNav">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#RequestForms" role="button"><span class="glyphicon glyphicon-bullhorn nav-icon"></span>{% trans "Requests" %}</a></li>
        <li><a href="{% url 'account:Account_screen' %}" id="AccountLink"><span class="glyphicon glyphicon-user nav-icon"></span>{% trans "Account Management" %}</a></li>
        <li><a href="{% url 'account:Logout' %}" id="LogoutLink">{% trans "Log out" %}</a></li>
      </ul>
    </div>
  </div>
</nav>

  <!-- Modal Test-->

parkering/kombo_parking/templates/kombo_parking/navbarForms.html
{% load i18n %}
<div id="RequestForms" class="ml-1">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href ="#hyra_ut" data-toggle="tab">{% trans "Rent-out space" %}</a>
        </li>
        <li href="#be_om_plats">
            <a href ="#be_om_plats" data-toggle="tab">{% trans "Request space" %}</a>
        </li>
    </ul>

    <div class="tab-content clearfix">
        <div class="tab-pane active booking-form" id="hyra_ut">
            <div id="wrapper">
                <form action="{%url 'kombo_parking:calendar' %}" method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}              

                    {{ rentout.as_p }}

                    <input class="hidden" name="form_content_check" value="rentout_parking_space">
                    <div class="footer">
                        <div>         
                            <input id="submit_button" class="btn btn-success green pull-right" role="button"  value="{% trans "Rentout" %}" type="submit" name="" />
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="tab-pane booking-form" id="be_om_plats">
            <div id="wrapper">
                <form action="{%url 'kombo_parking:calendar' %}" method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}

                    {{ request_form.as_p }}

                    <input class="hidden" name="form_content_check" value="request_parking_space">
                    <div class="footer">
                        <div>         
                            <input id="submit_button" class="btn btn-success green pull-right" role="button"  value="{% trans "Request" %}" type="submit" name="" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>