parkering/account/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [

    # display index screen
	url(r'^$', views.Index.Index_screen, name='Index_screen'),

    # used for login function
	url(r'^login/auth$', views.Login.Login_check, name='Login_check'),

    # used for logout function
	url(r'^logout$', views.Logout.Logout, name='Logout'),

    # display login screen
    url(r'^login$', views.Login.Login_screen, name='Login_screen'),

    # display register screen
    url(r'^register$', views.Register.Register_screen, name='Register_screen'),

    # display forgot password view
    url(r'^forgot_password$', views.ForgotPassword.Forgot_password_screen, name='Forgot_password_screen'),

    # used for register account function
    url(r'^register_account$', views.Register.Register_account, name='Register_account'),

    # display account management
    url(r'^account_management$', views.AccountManagement.Account_screen, name='Account_screen'),

    # display not authorized page
    url(r'^not_authorized$', views.Error.Authorization_failed, name='Authorization_failed'),

    # display update password page
    url(r'^update_password$', views.AccountManagement.UpdatePass_screen, name='UpdatePass_screen'),

    # used for update password function
    url(r'^update_password/update$', views.AccountManagement.Update_password, name='Update_password'),

    # display update password page
    url(r'^update_details$', views.AccountManagement.UpdateDetails_screen, name='UpdateDetails_screen'),

    # display update password page
    url(r'^update_details/update$', views.AccountManagement.Update_details, name='Update_details'),

    # the built-in password reset view.
    url(r'^reset_password$', views.ForgotPassword.Reset, name='reset'),
    
    # reset confirmation view, used with the password email reset link.
    url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.ForgotPassword.Reset_confirm, name='password_reset_confirm'),
]

parkering/main/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'main'

urlpatterns = [

	# display index view
    url(r'^$', views.Let_there_be_light, name='Render_all'),    

    # display FAQ
    url(r'^faq$', views.FAQ_screen, name='FAQ_screen'),

    # display test view
    url(r'^test$', views.Test, name='Test'),
]

parkering/parkering/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index')
]

parkering/parking/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^', include('account.urls')),
    url(r'^', include('kombo_parking.urls')),
]

parkering/main/models.py
from django.db import models

# Create your models here.

parkering/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Render account login/registration page on request
def Let_there_be_light(request):
    # return render(request, 'main/base.html')
    if request.user.is_authenticated():
        # return redirect("/frontpage")
        return redirect("/calendar")
    else:
        return render(request, "main/base.html")

# render FAQ page on request
def FAQ_screen(request):
    return render(request, 'main/information/FAQ_screen.html')

# development page for testing
def Test(request):
    return render(request, 'dev/test.html')

parkering/main/templates/main/information/FAQ_screen.html
<!-- FAQ view -->
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    {% include 'nexus/Nexus.html' %}
    <title>FAQ</title>
  </head>

  <body class="jumbotron">
    <h1>FAQ</h1>
    <div id="faq-container">
      <div id="faq-center">
          <!--faq:1-->
          <h3 class="faq-header">What is Kombo?</h3>
          <p class="faq-text">
            Kombo is a system specificially designed to ease the communication between users when borrowing and lending one or more parking spaces to oneanother.
          </p>
          <!--faq:2-->
          <h3 class="faq-header">What can i do here?</h3>
          <p class="faq-text">
            Kombo is an easy navigable website where you can:
          </p>
          <ul class="faq-list">
            <li>
              Lend your parking space(s) to others by filling out a simple form.
            </li>
            <li>
              Borrow someone else's parking space by finding your preferred date within a calendar and click the "Borrow" button.
            </li>
            <li>
              Request parking space by clicking the "Request" button.
            </li>
          </ul>
          <p class="faq-text">Other actions that may be done:</p>
          <ul class="faq-list">
            <li>
              Create an account.
            </li>
            <li>
              Reset password by logging in and navigate to "Account", then click on "Update password".
            </li>
            <li>
              Update your information by navigating to "Account", then click "Update information".
            </li>
            <li>
              Change password by navigating to "Forgot password" and type in your e-mail address to send a one-use link to a secure password reset page.
            </li>
          </ul>
          <!--faq:3-->
          <h3 class="faq-header">Why can't i register an account?</h3>
          <p class="faq-text">
            Only users who have requested to use this website and provided their apartment number to the website administrator may register on this website. 
            furthermore each apartment number may only be used once, should you see an error displaying that your provided apartment number is already in use please check your input and try again. Should the problem persist it is advised to contact your site administrator as soon as possible to resolve this issue.
          </p>
          <!--faq:4-->
          <h3 class="faq-header">Why can't i log in?</h3>
          <p class="faq-text">
            Only registered users may log in by providing the username and password they chose upon registration.
          </p>
          <!--faq:5-->
          <h3 class="faq-header">I forgot my password, how can i retrieve it?</h3>
          <p class="faq-text">
            If you have forgot your password you may click on the "Forgot password" button or "Forgot your password?" link. 
            You will then be redirected to a page where you may type the e-mail address you used to register your account.
            If the e-mail exists you will recieve an e-mail with a one-use link leading to a secure page where you may reset your password.
          </p>
          <!--faq:6-->
          <h3 class="faq-header">I have forgotten my login details and e-mail address, what should i do?</h3>
          <p class="faq-text">
            Should you forget your login details, you should at first try to recover your password/username through the "Forgot password" functionality. If this is not possible you should contact your site administrator to resolve this issue.
          </p>
      </div>
    </div>
    <!--faq:return-->
      <a href="{% url 'account:Index_screen' %}" class="btn btn-success green"  id="faq-return" role="button">Return</a>
  </body>
</html>